# In: ~/.gemini/commands/git/commit.toml
# Invoked via: /git:commit

description = "Automatically stages all changes and commits them to the local Git repository with a standardized commit message, then rewrites the message with custom rules."
prompt = """
1. Stage **all changes** in the repository (including modified and untracked files).
2. Analyze the full set of changes and generate a clear, conventional commit message
   following the style guide defined in @specifications/git_standards.md.
3. Commit all changes **to the local Git repository** with the generated message, **without asking for confirmation**.
4. After committing, must run the script `bash scripts/clean_commit.sh` to rewrite and clean up the commit message.
5. If there are no changes to commit, print: "No changes to commit."
"""
